def to_static_demo_data(bundle):
    signals = bundle.get("signals", [])
    mainline_id = "ML-P0-001"
    council_id = "COUNCIL-P0-001"
    report_id = "REPORT-P0-001"
    tasks = []
    if bundle.get("reports"):
        tasks = bundle["reports"][0].get("tasks", [])
    top_signal = signals[0] if signals else None
    metrics = _dashboard_metrics(signals)
    return {
        "case": {
            "id": "CASE-P0-001",
            "slug": "p0-network-signal-loop",
            "title": "P0 network signal collection and worldline loop",
            "mainlineId": mainline_id,
            "worldStateId": "WS-P0-001",
            "councilId": council_id,
            "reportId": report_id,
            "updatedAt": bundle.get("generatedAt"),
            "boundary": "Generated by P0 Agent Runtime. It uses only public, authorized, contracted, or manually uploaded records and requires human confirmation for high-risk conclusions.",
        },
        "dashboard": {
            "metrics": metrics,
            "goldenFeatureId": top_signal["id"] if top_signal else None,
        },
        "signals": signals,
        "mainlines": bundle.get("mainlines", []),
        "worldStates": bundle.get("worldStates", []),
        "worldlineNodes": bundle.get("worldlineNodes", []),
        "agents": _default_agents(),
        "councilResults": bundle.get("councilResults", []),
        "reports": [
            {
                **report,
                "documents": [
                    "P0 signal evidence packet",
                    "P0 world state summary",
                    "P0 council pressure test",
                    "P0 action task list",
                ],
            }
            for report in bundle.get("reports", [])
        ],
        "tasks": tasks,
    }


def to_static_map_layers(bundle):
    event_points = bundle.get("mapLayers", {}).get("eventPoints", {"type": "FeatureCollection", "features": []})
    heat_zones = bundle.get("mapLayers", {}).get("heatZones", {"type": "FeatureCollection", "features": []})
    center = [120.1551, 30.2741]
    if event_points.get("features"):
        center = event_points["features"][0]["geometry"]["coordinates"]
    risk_areas = {
        "type": "FeatureCollection",
        "features": [
            {
                **feature,
                "id": f"area-{feature['id']}",
                "properties": {
                    **feature.get("properties", {}),
                    "featureId": f"area-{feature['id']}",
                    "featureType": "risk-area",
                    "tone": _tone(feature.get("properties", {}).get("riskScore", 0)),
                    "eventCount": feature.get("properties", {}).get("signalCount", 1),
                    "sentiment": "derived from collected signals",
                    "spreadDensity": "P0 generated",
                    "breakoutProbability": f"{int(feature.get('properties', {}).get('riskScore', 0))}%",
                    "responseGap": "human review required before formal use",
                },
            }
            for feature in event_points.get("features", [])
        ],
    }
    return {
        "caseId": "p0-network-signal-loop",
        "config": {
            "center": center,
            "zoom": 12.4,
            "minZoom": 10,
            "maxZoom": 16,
            "maxBounds": [[120.06, 30.20], [120.27, 30.35]],
            "attribution": "Generated P0 map layer",
        },
        "riskAreas": risk_areas,
        "eventPoints": event_points,
        "spreadRoutes": {"type": "FeatureCollection", "features": []},
        "impactAreas": {"type": "FeatureCollection", "features": []},
        "heatZones": heat_zones,
    }


def to_static_geo_points(bundle):
    features = bundle.get("mapLayers", {}).get("eventPoints", {}).get("features", [])
    return {
        "caseId": "p0-network-signal-loop",
        "points": [
            {
                "id": feature["id"],
                "name": feature.get("properties", {}).get("title", feature["id"]),
                "type": feature.get("properties", {}).get("featureType", "event-point"),
                "coordinates": feature.get("geometry", {}).get("coordinates", [0, 0]),
                "regionId": feature.get("properties", {}).get("regionId", "unknown"),
            }
            for feature in features
        ],
    }


def _dashboard_metrics(signals):
    if not signals:
        return []
    top_heat = max(signal["scores"]["onlineHeat"] for signal in signals)
    top_risk = max(signal["scores"]["mainlineRisk"] for signal in signals)
    avg_credibility = sum(signal["scores"]["factCredibility"] for signal in signals) / len(signals)
    return [
        {"id": "risk-index", "label": "Mainline risk", "value": f"{int(top_risk)}/100", "delta": "P0", "tone": _tone(top_risk)},
        {"id": "new-signals", "label": "Signals", "value": str(len(signals)), "delta": "generated", "tone": "blue"},
        {"id": "online-heat", "label": "Online heat", "value": f"{int(top_heat)}/100", "delta": "sample", "tone": _tone(top_heat)},
        {"id": "fact-credibility", "label": "Fact credibility", "value": f"{int(avg_credibility)}/100", "delta": "review", "tone": _tone(avg_credibility)},
    ]


def _default_agents():
    return [
        {"id": "agent-stakeholder", "name": "Direct stakeholders", "stance": "Need facts, evidence, and a clear communication channel.", "tone": "red"},
        {"id": "agent-authority", "name": "Responsible authority", "stance": "Needs verification, response rhythm, and accountable task ownership.", "tone": "blue"},
        {"id": "agent-public", "name": "Public and media", "stance": "Tracks narrative gaps, responsibility claims, and response credibility.", "tone": "green"},
        {"id": "agent-platform", "name": "Platform and data source", "stance": "Focuses on data access boundaries, privacy, and abnormal spread.", "tone": "violet"},
    ]


def _tone(score):
    if score >= 80:
        return "red"
    if score >= 60:
        return "amber"
    return "green"
